apiVersion: apps/v1
kind: Deployment
metadata:
  name: maintenance
spec:
  replicas: 1
  selector:
    matchLabels:
      maintenance: "true"
  template:
    metadata:
      name: maintenance
      labels:
        maintenance: "true"
    spec:
      imagePullSecrets:
        - name: gcr-service-account
      containers:
        - name: nginx
          image: gcr.io/g5-images/maintenance-page:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "10m"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 3
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 3
            failureThreshold: 5
